#chiamata per avere i commenti relativi al post con ID

GET  http://localhost:5050/comments/post/64e7617ba1e426914852e168

#####

#Chiamata per avere tutti i commenti
GET http://localhost:5050/comments

#####


#chiamata POST per pubblicare un commento

POST  http://localhost:5050/comments/create HTTP/1.1
Content-Type: application/json

{
    "userName": "64d7bfc079d1ed9985d8f80b",
    "postId":"64d53453d7a5325e9192b260",
    "content":"il desero del sahara e un eccellente meta per le proprie vacanze!!",
    "rating": 5
}

#####
PATCH  http://localhost:5050/comments/64bd8fa968a1306cf54f5dda HTTP/1.1
Content-Type: application/json

{
    "content":"libro poco interessante(commento modificato con patch)"
}


#####

DELETE http://localhost:5050/comments/64bd8fa968a1306cf54f5dda 