#chiamata per filtrare i post x titolo
GET http://localhost:5050/posts/title?postTitle=terzo
#####


#chiamata per avere tutti i post

GET http://localhost:5050/posts/?pageSize=1000
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidXRlbnRlIHByb3ZhIGxvZ2luIiwic3VybmFtZSI6ImxvZ2luIiwiYmlydGhkYXlEYXRlIjoiMTMgZ2l1Z25vIDE5OTAiLCJhdmF0YXIiOiJtYXJpbyIsImlhdCI6MTY5MTM1MTM2NCwiZXhwIjoxNjkxNDM3NzY0fQ.ZUTJ2CcgkNMhz15I6LGK1_FQR5coqwHXti_bce9nUv0
installHook.js:251 
#####

POST http://localhost:5050/posts/create HTTP/1.1
Content-Type: application/json

{
    "category": "horror",
    "title": "post referencing created number 2",
    "cover":"https://www.pngplay.com/wp-content/uploads/13/Pngpix-Transparent-PNG.png" ,
    "readTime": {
        "value": 10,
        "unit": "minutes"
    },
    "author": "64b97e29b91473faea476fd9",
    "content": "primo post con validation pubblicato con successo !"
}

#####

DELETE http://localhost:5050/posts/64b0706ff038a30c43acb941


##### 

PATCH http://localhost:5050/posts/64b0703ad74dc7a28bfd147f
Content-Type: application/json

{
    "category": "fantasy",
    "title": " io sono il post modificato con il patch"
}